//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySachDatabaseFirst.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_HoaDon
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public int MaSize { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Size Size { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
